@startuml
actor "Spring Framework" as Framework
Framework -> SpringApplication: getSpringFactoriesInstances(interfaceType)
activate SpringApplication
SpringApplication -> SpringFactoriesLoader: loadFactoryNames(interfaceType, classLoader)
activate SpringFactoriesLoader
SpringFactoriesLoader -> ClassLoader: getResources("META-INF/spring.factories")
ClassLoader --> SpringFactoriesLoader: urls
loop
SpringFactoriesLoader -> PropertiesLoaderUtils: loadProperties(url)
PropertiesLoaderUtils --> SpringFactoriesLoader: properties
SpringFactoriesLoader -> Properties: getProperty(interfaceName)
Properties --> SpringFactoriesLoader: instanceNames
end
SpringFactoriesLoader --> SpringApplication: instanceNames
deactivate SpringFactoriesLoader
SpringApplication -> SpringApplication: createSpringFactoriesInstances(..., instanceNames)
activate SpringApplication
SpringApplication --> SpringApplication: instances
deactivate SpringApplication
SpringApplication --> Framework: instances
deactivate SpringApplication
@enduml
