@startuml
interface Handler {
  +handle(request)
}
abstract class AbstractHandler
class HandlerWrapper
class ServletHandler
class HandlerContainer
class Server
class SessionHandler {
  +SessionManager
}
class SecurityHandler {
  +SecurityConstraint[]
}
class ContextHandler {
  +contextPath
  +resourceBase
  +classLoader
}
class ContextHandlerContainer {
  -contexts: PathMap
}
class WebAppContext {
  +descriptor
}

Handler <|.. AbstractHandler
Handler "1" --o HandlerWrapper
Handler "*" --o HandlerContainer
AbstractHandler <|-- HandlerWrapper
AbstractHandler <|-- ServletHandler
AbstractHandler <|-- HandlerContainer
AbstractHandler ..> Server
HandlerWrapper <|-- Server
HandlerWrapper <|-- SessionHandler
HandlerWrapper <|-- SecurityHandler
HandlerWrapper <|-- ContextHandler
ServletHandler <.. WebAppContext
HandlerContainer <|-- ContextHandlerContainer
SessionHandler <.. WebAppContext
SecurityHandler <.. WebAppContext
ContextHandler <. ContextHandlerContainer
ContextHandler <|-- WebAppContext
@enduml
